name: CI

on: push

jobs:
  gradle-build:
    name: 🏗️ Gradle build
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Check-out
        uses: actions/checkout@v5
      - name: 🧰 Install JDK
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: temurin
          cache: gradle
      - name: 🏗️ Build with Gradle
        run: ./gradlew build
  gradle-test:
    name: ✅ Gradle test
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Check-out
        uses: actions/checkout@v5
      - name: 🧰 Install JDK
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: temurin
          cache: gradle
      - name: ✅ Test with Gradle
        run: ./gradlew test
  github-release:
    name: 🚀 Create GitHub release
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    needs:
    - gradle-build
    - gradle-test
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: 📥 Check-out
      uses: actions/checkout@v5
    - name: 🚀 Create GitHub release
      uses: softprops/action-gh-release@v2
      with:
        name: Release ${{ github.ref_name }}
        fail_on_unmatched_files: true
        draft: false
        prerelease: false
        generate_release_notes: true